name: Godot CI
on:
  - push
  - workflow_dispatch

env:
  GODOT_VERSION: 4.3

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p exports/web
          godot --headless --verbose --export-release "Web" ./exports/web/index.html
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: exports/web

  deploy-web:
    runs-on: ubuntu-latest
    needs: [export-web]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


